### DISCUSSION TITLE
Changing battery widget color when < 5%

### DISCUSSION THREAD

**Discussion by AnirudhG07** [Jean-Tinland/simple-bar#432] [Ideas]
It would be great if we could like change the battery color widget from purple to RED or something custom so that it indirectly keeps pinging us after 5% reminder in Mac that battery is LOW.
Maybe like changing color every 1% since the change comes to notice or atleast when <= 5%, just change to RED.

What do you think? 
(If this already exists, pls share how to do so :)

**Comment by Jean-Tinland** [comment]
Sure, you can add these custom styles in your settings:

```css
.battery--low {
  background-color: var(--red);
}

.battery--low .battery__charging-icon {
  stroke: var(--red);
}
```

With these, the battery widget will turn red as soon as battery level drops under 15%.

Let me know if this is what you are looking for :)
