### ISSUE TITLE
Latest Update - Styling changes?

### ISSUE THREAD

**Issue by MikoMagni** [Jean-Tinland/simple-bar#179]
Hi Jean, 

I just pulled down your latest update and now simple-bar is several pixels taller, rounded corners everywhere and more padding. 

Seems to be happening with all themes.  Do we need to update themes?

**before**
<img width="729" alt="image" src="https://user-images.githubusercontent.com/2527231/121634206-4e898180-cac3-11eb-99ba-73d5482650ea.png">

**After** 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/2527231/128656991-4f7ca5b6-cf54-49f7-a093-cc52a0104fe5.png">

Thanks :)

**Comment by Jean-Tinland** [comment]
Oooops, I pushed my custom styles, I'm fixing this right away!

**Comment by Jean-Tinland** [comment]
Fixed! :)

**Comment by MikoMagni** [comment]
Awesome, thank you :)

**Comment by Tchoupinax** [comment]
> Oooops, I pushed my custom styles, I'm fixing this right away!

Oh noooooo! I love it! @Jean-Tinland Can you share it ? 

I was thinking it was an update with macOS Big sur 🤣  
Your custom styles are much more practical!

**Comment by Jean-Tinland** [comment]
You can add these to the `Custom styles` tab in settings:

```css
:root {
  --bar-height: 40px;
  --bar-radius: 12px;
  --item-radius: 8px;
  --bar-inner-margin: 6px ;
  --item-inner-margin: 3px 12px;
  --item-outer-margin: 0 0 0 6px;  
}
```

:)
