### ISSUE TITLE
change text-color

### ISSUE THREAD

**Issue by kocierik** [Jean-Tinland/simple-bar#247]
Can I change text color of my personal user widget?

**Comment by Jean-Tinland** [comment]
Hi!

I just added a custom class to each user-widget. You can now target each of your own widgets and apply them some custom styles.

For example:

```css
.simple-bar .data-widget.user-widget--1 {
  color: red !important;
}
```

You can get the specific class name by opening the Übersicht console:
![Screenshot 2021-11-10 at 14 55 24](https://user-images.githubusercontent.com/43068795/141126446-79f08cfa-79cb-43e6-8441-b412e38b43be.jpg)
