### ISSUE TITLE
Pin data to the right

### ISSUE THREAD

**Issue by kristiansordal** [Jean-Tinland/simple-bar#325]
I have a problem where I cannot figure out how to pin the data portion of my bar to the right, as seen in the picture, on the right side, the data is pinned on the left hand side, however I would like to pin it to the left.

![Pic](https://user-images.githubusercontent.com/94058487/200128443-b862d06f-c711-4092-b2be-46992574e8de.png)

How do I go about achieving this?

My configuration is as follows:

```
:root {
  --bar-height: 27px;
  --bar-radius: 14px;
  --item-radius: 8px;
  --bar-inner-margin: 6px;
  --item-inner-margin: 3px 12px;
  --item-outer-margin: 0 0 0 6px;
  --display: 50px;

}

.simple-bar--no-bar-background .spaces {
  min-width: 642px;
  alignSelf: 'flex-end';
}
.simple-bar--no-bar-background .simple-bar__data {
   min-width: 647px;
   alignSelf: 'flex-end';
}

```

**Comment by Jean-Tinland** [comment]
I think the css you are looking for is:

```css
.simple-bar--no-bar-background .spaces {
  min-width: 642px;
  justify-content: flex-start;
}
.simple-bar--no-bar-background .simple-bar__data {
  min-width: 647px;
  justify-content: flex-end;
}
```
