### ISSUE TITLE
Slide in animation

### ISSUE THREAD

**Issue by Jarvvski** [Jean-Tinland/simple-bar#4]
Hey there, love the bar.

I had a go at doing this myself, but my CSS-foo is not great and I'm a little lost.

Trying to replicate the effect found [here](https://tympanus.net/Development/LineMenuStyles/) (look at the first _alonso_ example).

Where, if I switch to a space to the right of the current space, then the the 'focussed' color slides to the right. _Towards_ the new space. Likewise, the opposite if the new space is to the left, the 'focussed' color slides to the _left_.

Any thoughts on this? I tried toying with the CSS, and potentially adding a rotate transform to the `::after` element, but I don't really know what I'm doing here.

**Comment by Jean-Tinland** [comment]
Hi Jarvvski,

I'm afraid that without a total revamp of my SpacesDisplay layout it would be impossible to implement such a behaviour.

In the provided example, each menu item has the same width so that the line under (which is a div in `absolute` position) has a `translate` function of the current menu item selected multiplied by `100%`. 

```html
<nav class="menu menu--alonso">
  <ul class="menu__list">
    <li class="menu__item"><a href="#" class="menu__link">Home</a></li>
    <li class="menu__item"><a href="#" class="menu__link">Gallery</a></li>
    <li class="menu__item menu__item--current"><a href="#" class="menu__link">Portfolio</a></li>
    <li class="menu__item"><a href="#" class="menu__link">Clients</a></li>
    <li class="menu__item"><a href="#" class="menu__link">Contact</a></li>
    <li class="menu__line"></li>
  </ul>
</nav>
```

```css
.menu--alonso .menu__item:nth-child(3).menu__item--current ~ .menu__line {
    transform: translate3d(200%, 0, 0);
}
.menu--alonso .menu__line {
    position: absolute;
    top: 100%;
    left: 0;
    width: 120px;
    height: 2px;
    pointer-events: none;
    border: 1px solid #fff;
    border-width: 0 45px;
    background: #d94f5c;
    transition: transform 0.5s cubic-bezier(1, 0.01, 0, 1.22);
}
```

In our use case, each space has a variable width depending on the active apps in it. So in order to determine the current position of the indicator (the line), we would need to calculate its width and its offset from left when the user clicks on a space.

I'm not comfortable enough with Übersitch to apprehend the implementation logic of this but I certainly will give it a go in the future.

Sorry for my late answer I was enjoying my vacations away from my keyboard :)
