### ISSUE TITLE
Colour scheme override GUI 

### ISSUE THREAD

**Issue by coderzawad** [Jean-Tinland/simple-bar#429]
So i am a huge fan of catpuccin mocha and tokyongiht colour scheme. 
And my entire setup is based on tokyo-night theme.

So i'd really love to have the option to change my colour-scheme.
There should be few presets like tokyo night, catpuccin all flavours.

There is theme option but it doesn't really changes the colours it just changes the appearence abit and just the foreground and few text colours so i'd love to see colour schemees.

**Comment by Jean-Tinland** [comment]
I'm not sure what you would like to change more than the existing themes are already doing.

I may not understand what you are asking, but have you tried to apply some custom CSS on top of your selected theme [as explained here](https://www.jeantinland.com/toolbox/simple-bar/documentation/custom-styles/)?

In short, if you paste this in your custom CSS tab in settings, you'll be able to override every color used in simple-bar:

```css
:root {
  --main: #1b222d;
  --main-alt: #98a8c5;
  --minor: #39465e;
  --accent: var(--yellow);
  --red: #e78482;
  --green: #8fc8BB;
  --yellow: #ffd484;
  --orange: #ffb374;
  --blue: #6db3cE;
  --magenta: #ad82cB;
  --cyan: #7eddde;
  --black: #1b222d;
  --white: #fff;
  --foreground: var(--white);
  --background: var(--main);
  --transparent-dark: rgba(0, 0, 0, 0.05);
  --font: "JetBrains Mono", Monaco, Menlo, monospace;
  --font-size: 11px;
  --bar-height: 34px;
  --bar-radius: 6px;
  --bar-border: 0px solid transparent;
  --bar-inner-margin: 3px;
  --item-max-width: 160px;
  --item-radius: 5px;
  --item-inner-margin: 3px 7px;
  --item-outer-margin: 0 0 0 5px;
  --hover-ring: 0 0 0 2px rgba(255, 255, 255, 0.75);
  --focus-ring: 0 0 0 2px rgb(255, 255, 255);
  --light-shadow:0 5px 10px rgba(0, 0, 0, 0.24);
  --foreground-shadow: 0 0 0 1px var(--foreground);
  --transition-easing: cubic-bezier(0.4, 0, 0.2, 1);
  --click-effect: rgba(255, 255, 255, 0.3);
}
```
