### ISSUE TITLE
simple-bar keeps ProMotion displays at 120Hz: option to disable animations?

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#453]
**Is your feature request related to a problem? Please describe.**
I just realized that simple-bar was keeping the ProMotion display at 120Hz because of the weather widget's animations. Using the caffeinate feature also makes this occur.

**Describe the solution you'd like**
I wish there was a checkbox to disable all animations, aside from the spinning loading icon ones.

**Describe alternatives you've considered**
I currently use this custom CSS, which is a bit of a nuclear option but works and allows ProMotion displays to decrease in refresh rate.
```css
.battery__caffeinate-icon *,
.weather *,
.specter *,
.missive--left,
.missive--right {
    animation: none !important;
}
```
